// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public enum ENPCTriggerType
{
	Disappear = 1,
	Appear = 2,
	ActivateMover = 3,
	DoNothing = 4,
	EnableComponent = 5,
	DisableComponent = 6,
	DisableBoxCollider2D = 7,
	EnableBoxCollider2D = 8,
	SetAnimationValue = 9,
}


