//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Battles
{
	public enum EMonsterAnimations
	{
		Idle = 0,
		Rest = 1,
		Walk = 2,
		Run = 3,
		Flying = 4,
	}
}

