// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Battles
{
	public enum EMonsterStat
	{
		RangeAttack = 1,
		MeleeAttack	= 2,
		RangeDefense = 4,
		MeleeDefense = 8,
		Accuracy = 16,
		Speed = 32,
		Agility = 64,
		Support = 128,
		
	}
}

