// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
[Flags]
public enum EMoveFlag
{
	Idle = 0x00,
	Moving = 1,
	BeingHit = 2,
	BeingBaited = 4,
	BeingCaught = 8,
	BeingSwapped = 16,
	Fainting = 32,
	GainingXP = 64,
	ResistanceChanging = 128,
	BeingConfused = 256,
	FallingAsleep = 512,
	BeingFrozen = 1024,
	BeingParalyzed = 2048,
	BeingPoisoned = 4096,
	BeingBurned = 8192,
	BeingSeeded = 16384,
	StatsRaising = 32768,
	StatsFalling = 65536,
	FadingIn = 131072,
	HealthChanging = 262144,
	EnviroEffecting = 524288,
	EnergyChanging = 2097152,
	AnyStatusEffecting = 1048576,
	
	//16,811,058
}


