// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Battles
{
	[Flags]
	public enum EMoveQueueItemStatus
	{
		Start = 0,
		ChangeToOtherMove = 1,
		AttackAnimation =2,
		HPHits = 3,
		HPHitsPassiveEffects = 4,
		StatusEffects = 5,
		HPBoosts = 6,
		StatusBoosts = 7,
		StatEffectors = 8,
		MoveBackToPosition = 9,
		InflictMyEffects = 10,
		EndMoveQueuePassiveEffects = 11,
		Finish = 12,
	}
}
