//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Battles
{
	[Flags]
	public enum EOrbitCamOptions
	{
		NeverUse = 0,
		BattleStart = 1,
		OnTurnStart = 2,

	}
}

