// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Battles
{
	[Flags]
	public enum EReadyForNextTurnStatus
	{
		Ready = 0x00,
		MovesUnset = 0x01,
		NoMonsters = 0x02,
		
	}
}

