// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Battles
{
		[Flags]
		public enum ETeamControllerType
		{
			SinglePlayerUser = 0x01,
			MultiplayerUser = 0x02,
			RegularAI = 0x04,
			PartyTeam = 0x08,
			WildAI = 0x16,
		}
		
}

