// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Battles
{
		public enum ETeamPosition
		{
			UnSet = 0,
			LeftTeam = 1,
			RightTeam = 2,
		MonsterPreview = 3,
		MonsterPreviewRight = 4,
		}
}

