// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using Items;
 

namespace Battles
{
	public class BattleBase : MonoBehaviour
	{
		public GameObject commentaryEngine;
		protected CommentaryManager _commentaryManager;
		protected InventoryDisplay _inventory;
		protected MoveQueueItem _currentItem;
		public CameraPath teamACameraPath;
		public CameraPath teamBCameraPath;
		public UILabel debugText;
		
		public Camera UICamera;
		public Camera GlobalCamera;
		public GameObject blackScreen;
		public BattleOverScreen battleOverScreen;
	
		private GameObject _background; 
		public MultiplayerCountdownTimer countdownTimer;
		public static int DEBUG_COUNT = 0;
		public static int MULTIPLAYER_DEBUG_COUNT = 0;
		protected bool _battleComplete = false;
		
		protected BetterList<MoveQueueItem> _moveQueue;
		
		public static int COST_TO_CONTINUE = 10;
		public GameObject continueBattleScreen;


		public EOrbitCamOptions orbitCamera; 
		public BattleBase ()
		{

		}
		

		public void setCamera(GameObject aCameraContainer,EMonsterCamPosition aCamPosition,bool aImmediateLookAt,bool aImmediateStickTo,bool aOnlyMoveTo,Transform aLookAt) {
			
			string findCam = "";
			switch (aCamPosition) {
			case(EMonsterCamPosition.ChaseCamera):findCam = "CameraMount";break;
			case(EMonsterCamPosition.SideCamera):findCam = "SideCameraMount";break;
			case(EMonsterCamPosition.FrontCamera):findCam = "FrontCameraMount";break;
			case(EMonsterCamPosition.FrontSide):findCam = "FrontSideMount";break;
			case(EMonsterCamPosition.TVCamera):findCam = "TVCamMountMiddle";break;
			}
			/*
			 * 
			 */ 
		if(aLookAt!=null) {
			Transform t = aLookAt.FindChild("HeadPoint");
			if(t!=null) {
				aLookAt = t;
			}
		}
			CameraTrack c = this.GetComponent<CameraTrack> ();
			if (aCameraContainer == null) {
				c.stickTo = null;
				c.target = aLookAt;
				return;
			}
		
			Transform camHolder = aCameraContainer.transform.FindChild (findCam);
			if(findCam=="TVCamMountMiddle") {
				camHolder = GameObject.Find ("TVCamMountMiddle").transform;
			}

			if(camHolder == null) {
				return;
			}
			if (aOnlyMoveTo) {
				this.gameObject.transform.position = camHolder.transform.position;
			} else {
				c.stickTo = camHolder;
			}
			if (aImmediateStickTo) {
				c.immediateStick();
			}
			if (aLookAt != null) {
				c.target = aLookAt;
			}
			if (aImmediateLookAt && aLookAt != null) {
				c.immediateLook();
			}
			
		}

		public bool moveQueueActive {
			get {
				if(_moveQueue!=null) {
					if(_moveQueue.size>0) {
						if(_currentItem!=null) {
							return true;
						}
					}
				}
				return false;
			}
		}
		
		public void addDebug(string aText) {
			if(debugText!=null) {
				debugText.text += "\n "+aText;
			}
			DebugText(aText);
		}
		public static void DebugText(string aText,Color aColor) {
			GameObject debugWindow = GameObject.FindGameObjectWithTag("BattleDebugger");
			if(debugWindow!=null) {
				UITextList list = debugWindow.GetComponent<UITextList>();
				MULTIPLAYER_DEBUG_COUNT++;
		//		list.Add("[" + NGUIText.EncodeColor(aColor) + "]"+MULTIPLAYER_DEBUG_COUNT+": "+aText);
			}
		}
		public static void DebugText(string aText) {
			GameObject debugWindow = GameObject.FindGameObjectWithTag("BattleDebugger");
			if(debugWindow!=null) {
				UITextList list = debugWindow.GetComponent<UITextList>();
				
				DEBUG_COUNT++;
			//	list.Add(DEBUG_COUNT+"(Turn: "+BattleControllerWithMoveQueue.MOVE_TURN+"): "+aText);
			}
		}
		public static void QueueText(string aText) {
			GameObject debugWindow = GameObject.FindGameObjectWithTag("BattleDebugger");
			if(debugWindow!=null) {
				UITextList list = debugWindow.GetComponent<UITextList>();
				
				DEBUG_COUNT++;
				list.Add(DEBUG_COUNT+"(Turn: "+BattleControllerWithMoveQueue.MOVE_TURN+"): "+aText);
			}
		}
		public static void MultiplayerDebugText(string aText) {
			GameObject debugWindow = GameObject.FindGameObjectWithTag("MultiplayerBattleDebugger");
			if(debugWindow!=null) {
				UITextList list = debugWindow.GetComponent<UITextList>();
				MULTIPLAYER_DEBUG_COUNT++;
				list.Add(MULTIPLAYER_DEBUG_COUNT+" (Turn: "+BattleControllerWithMoveQueue.MOVE_TURN+"): "+aText);
			}
		}
		
		protected void baseCreate() {
			
				if(commentaryEngine!=null) {
					_commentaryManager = commentaryEngine.GetComponent<CommentaryManager>();
					}
				if(BattleInit.REF!=null) // We might be a multiplayer game
				_background = BattleBGLibrary.getBattleBG(BattleInit.REF.battleBackground);
				
				blackScreen.GetComponent<Renderer>().sortingLayerName = "MiddleLayer";
				blackScreen.transform.localScale = new Vector3(Screen.width*2,Screen.height*2,1);
			}
			

		
			
		}
}

