// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;


namespace Battles
{
	public class BattleControllerWithParticleEngines : BattleBase
	{
		public BattleControllerWithParticleEngines ()
		{
		}
		protected IEnumerator pauseForAttack(MoveQueueItem aMoveQueueItem,float aSeconds) {
			BetterList<BattleMonster> allTargets = aMoveQueueItem.targettedMonster;
			
			for(int i = 0;i<allTargets.size;i++) {
				
				if(aMoveQueueItem.moveData!=null) {
					if(!aMoveQueueItem.moveData.isBoost) {
						
						allTargets[i].doDefenseAnimation(this._currentItem);
					} else {
						 
						allTargets[i].doDefenseAnimation(this._currentItem);
					}
				}
			}
			
			yield return new WaitForSeconds(aSeconds);
			
			this.GetComponent<CameraTrack> ().target = null;
			this.GetComponent<CameraTrack> ().stickTo = null;

			aMoveQueueItem.advanceMoveQueueFromState(EMoveQueueItemStatus.AttackAnimation);
		}
		protected virtual void unpackInitData() {
			

		}
		public static void putParticlesInfront() {
			GameObject[] allParticles = GameObject.FindGameObjectsWithTag("ParticleSystems");
			for(int i = 0;i<allParticles.Length;i++) {
				
				allParticles[i].GetComponent<ParticleSystem>().GetComponent<Renderer>().sortingLayerName = "ParticleLayer";
				ParticleSystem[] children = allParticles[i].GetComponentsInChildren<ParticleSystem>();
				for(int j = 0;j<children.Length;j++) {
					children[j].GetComponent<Renderer>().sortingLayerName = "ParticleLayer";
				}
			}
		}
		
	}
}

