// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Battles
{
	public class BattleTeamWithAI : BattleTeamWithMoves
	{
		public BattleTeamWithAI ()
		{
		}
		
		public void turnIntoAI() {
			this.teamType = ETeamControllerType.RegularAI;
		}
		public void selectAIMoves() {
			while(nextUnsetMonster!=null) {
				nextUnsetMonster.setAIFutureMove(this.teamPosition);
			}
		}
		
		public void autoSelectMoves() {
			while(nextUnsetMonster!=null) {
				nextUnsetMonster.setAIFutureMove(this.teamPosition);
			}
		}
	}
}

