// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using Google2u;
using System.Collections.Generic;
using UnityEngine;
public class MoveTree
{
	private BetterList<MoveTreeItem> _moves = new BetterList<MoveTreeItem>();
	private string _name;
	private int _id;
	private string _displayName;
	public MoveTree (MoveTreesRow aInitData)
	{
		_name = aInitData._Name;
		_id = aInitData._ID;
		_displayName = aInitData._DisplayName;

		List<MoveTreeDataRow> moveTrees = MoveTreeData.Instance.Rows;

		for (int i = 0; i < moveTrees.Count; i++) {
			if( moveTrees[i]._MoveTree == _name) {
				_moves.Add(new MoveTreeItem(moveTrees[i]));
			}
		}
		for (int i = 0; i < _moves.size; i++) {
			_moves[i].initPreceedingMove(_moves);		
		}
	}

	public BetterList<MoveTreeItem> Moves {
		get {
			return _moves;
		}
	}
	
	public string DisplayName {
		get {
			return _displayName;
		}
	}
	public string Name {
		get {
			return _name;		
		}
	}
}
