// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Google2u;
using UnityEngine;
using Battles;


namespace Items
{
	public class BattleBoostItem : ItemGeneric
	{
		public float multiplierVal = 1f;
		public int weaknessBinaryVal = 0;
		public int statChangeBinaryVal = 0;
		public float accuracyMulti = 1f;
		public float agilityMulti = 1f;
		public float rangeAtckMulti =1f;
		public float rangeDefMulti = 1f;
		public float meleeAtckMulti = 1f;
		public float meleeDefMulti =1f;
		public float speedMulti = 1f;
		public float criticalHitMulti = 1f;
		public BattleBoostItem (ItemsBattleBoostsRow aRow)
		{
			_name = aRow._itemname;
			_description = aRow._itemdescription;
			_tintColour = new Color(aRow._spritetintr/255,aRow._spritetintg/255,aRow._spritetintb/255,aRow._spritetinta/255);
			_spritePrefab = aRow._sprite;
			this._softCost = aRow._softcurrency;
			this._hardCost = aRow._hardcurrency;
			switch(aRow._boosttype) {
				/*BoostAccuracy,BoostAgility,BoostRangeAtck,BoostRangeDef,BoostMeleeAtck,BoostMeleeDef,BoostSpeed,BoostAll
				RemoveWeaknessTo,InvulnerableToStatChange,CriticalHitMultiplier
				*/
				case("BoostAccuracy"):accuracyMulti = aRow._boostpercent;break;
				case("BoostAgility"):agilityMulti = aRow._boostpercent;break;
				case("BoostRangeAtck"):rangeAtckMulti = aRow._boostpercent;break;
				case("BoostRangeDef"):rangeDefMulti = aRow._boostpercent;break;
				case("BoostMeleeAtck"):meleeAtckMulti = aRow._boostpercent;break;
				case("BoostMeleeDef"):meleeDefMulti = aRow._boostpercent;break;
				case("BoostSpeed"):speedMulti = aRow._boostpercent;break;
				case("BoostAll"):accuracyMulti = aRow._boostpercent;
								agilityMulti = aRow._boostpercent;
								rangeAtckMulti = aRow._boostpercent;
								rangeDefMulti = aRow._boostpercent;
								meleeAtckMulti = aRow._boostpercent;
								meleeDefMulti = aRow._boostpercent;
								speedMulti = aRow._boostpercent;
				break;
				case("RemoveWeaknessTo"):weaknessBinaryVal = Convert.ToInt32(aRow._boostpercent);break;
				case("InvulnerableToStatChange"):weaknessBinaryVal = Convert.ToInt32(aRow._boostpercent);break;
				case("CriticalHitMultiplier"):weaknessBinaryVal = Convert.ToInt32(aRow._boostpercent);break;
				
			}
			this._id = aRow._id;
			_itemType = EItemType.BattleBoost;
		}
		
		public int removesWeaknessesTo {
			get {
				return weaknessBinaryVal;
			}
		}
		public float accuracyMultiplier {
			get {
				return multiplierVal;
			}
		}
		public float agilityMultiplier {
			get {
				return multiplierVal;
			}
		}
		public float rangeAtck {
			get {
				return multiplierVal;
			}
		}
		
		public float rangeDef {
			get {
				return multiplierVal;
			}
		}
		public float meleeAtck {
			get {
				return multiplierVal;
			}
		}
		
		public float meleeDef {
			get {
				return multiplierVal;
			}
		}
		
		public float speed {
			get {
				return multiplierVal;
			}
		}
		
		public EMonsterStat invulnerableToStatChange {
			get {
				return (EMonsterStat) statChangeBinaryVal;
			}
		}
		
		public float decisiveBlowsChangeMultiplier {
			get {
				return multiplierVal;
			}
		}
	}
}

