// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Items
{
	[Flags]
	public enum EInventoryType
	{
		Worldview = 1,
		Battleview = 2,
		Ranchview = 4,
		Tradeview = 8,
		BaitView = 16,
		
	}
}

