// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Items
{
	[Flags]
	public enum EItemRecoveryType
	{
		HealValue = 0x01,
		HealPercentage = 0x02,
		DamageValue = 0x04,
		DamagePercentage = 0x08,
	}
}

