// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Items
{
	[Flags]
	public enum EItemType
	{
		Bait = 1,
		Collar = 2,
		Vitamin = 4,
		Recovery = 8,
		BattleBoost = 16,
		Quest = 32,
		PlayerBoost = 64,
		
	}
}

