// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Google2u;
using UnityEngine;


namespace Items
{
	public class ItemRecoveryItem : ItemGeneric
	{
		private BetterList<RecoveryTriplet> _recoveryTypes = new BetterList<RecoveryTriplet>();
		public ItemRecoveryItem (ItemsRecoveryRow aRecoveryRow)
		{
			_name = aRecoveryRow._ItemName;
			_id = aRecoveryRow._ID;
			_description = aRecoveryRow._ItemDescription;
			_tintColour = new Color(aRecoveryRow._SpriteTintR/255,aRecoveryRow._SpriteTintG/255,aRecoveryRow._SpriteTintB/255,aRecoveryRow._SpriteTintA/255);
			_spritePrefab = aRecoveryRow._Sprite;
			this._hardCost = aRecoveryRow._HardCurrency;
			this._softCost = aRecoveryRow._SoftCurrency;
			_itemType = EItemType.Recovery;
			_recoveryTypes.Add(new RecoveryTriplet(aRecoveryRow._ToRecoverA,aRecoveryRow._RecoverAType,aRecoveryRow._RecoverAValue));
			if(aRecoveryRow._ToRecoverB!=null) 
				_recoveryTypes.Add(new RecoveryTriplet(aRecoveryRow._ToRecoverB,aRecoveryRow._RecoverBType,aRecoveryRow._RecoverBValue));
			
		}
		/*
		
			switch(aRecoverArea) {
				case("HP"):recoveryArea = EItemRecoveryArea.HP;break;
				case("Energy"):recoveryArea = EItemRecoveryArea.Energy;break;
				case("Heal All Status"):recoveryArea = EItemRecoveryArea.HealAllStatus;break;
				case("Heal Burn"):recoveryArea = EItemRecoveryArea.Burn;break;
				case("Heal Freeze"):recoveryArea = EItemRecoveryArea.Freeze;break;
				case("Heal Confusion"):recoveryArea = EItemRecoveryArea.Confusion;break;
				case("Heal Paralyzed"):recoveryArea = EItemRecoveryArea.Paralyzed;break;
				case("Heal Poisoned"):recoveryArea = EItemRecoveryArea.Poison;break;
			}
			
			switch(aRecoverType) {
				
				case("HealValue"):recoveryType = EItemRecoveryType.HealValue;break;
				case("HealPercentage"):recoveryType = EItemRecoveryType.HealValue;break;
				case("DamagePercentage"):recoveryType = EItemRecoveryType.DamagePercentage;break;
				case("DamageValue"):recoveryType = EItemRecoveryType.DamageValue;break;
			}
			*/
		public RecoveryTriplet healsHP {
			get {
				for(int i = 0;i < _recoveryTypes.size;i++) {
					if(_recoveryTypes[i].recoveryArea==EItemRecoveryArea.HP) {
						return _recoveryTypes[i];
					}
				}
				return null;
			}
		}
		public RecoveryTriplet restoresEnergy {
			get {
				for(int i = 0;i < _recoveryTypes.size;i++) {
					if(_recoveryTypes[i].recoveryArea==EItemRecoveryArea.Energy) {
						return _recoveryTypes[i];
					}
				}
				return null;
			}
		}
		public RecoveryTriplet healsBurn {
			get {
				for(int i = 0;i < _recoveryTypes.size;i++) {
					if((_recoveryTypes[i].recoveryArea==EItemRecoveryArea.Burn)||(_recoveryTypes[i].recoveryArea==EItemRecoveryArea.HealAllStatus)) {
						return _recoveryTypes[i];
					}
				}
				return null;
			}
		}
		public RecoveryTriplet healsConfusion {
			get {
				for(int i = 0;i < _recoveryTypes.size;i++) {
					if((_recoveryTypes[i].recoveryArea==EItemRecoveryArea.Confusion)||(_recoveryTypes[i].recoveryArea==EItemRecoveryArea.HealAllStatus)) {
						return _recoveryTypes[i];
					}
				}
				return null;
			}
		}
		public RecoveryTriplet healsFreeze {
			get {
				for(int i = 0;i < _recoveryTypes.size;i++) {
					if((_recoveryTypes[i].recoveryArea==EItemRecoveryArea.Freeze)||(_recoveryTypes[i].recoveryArea==EItemRecoveryArea.HealAllStatus)) {
						return _recoveryTypes[i];
					}
				}
				return null;
			}
		}
		public RecoveryTriplet healsParalysis {
			get {
				for(int i = 0;i < _recoveryTypes.size;i++) {
					if((_recoveryTypes[i].recoveryArea==EItemRecoveryArea.Paralyzed)||(_recoveryTypes[i].recoveryArea==EItemRecoveryArea.HealAllStatus)) {
						return _recoveryTypes[i];
					}
				}
				return null;
			}
		}
		public RecoveryTriplet healsPoison {
			get {
				for(int i = 0;i < _recoveryTypes.size;i++) {
					if((_recoveryTypes[i].recoveryArea==EItemRecoveryArea.Poison)||(_recoveryTypes[i].recoveryArea==EItemRecoveryArea.HealAllStatus)) {
						return _recoveryTypes[i];
					}
				}
				return null;
			}
		}
		
	}
}

