// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Google2u;
using UnityEngine;


namespace Items
{
	public class ItemVitamin : ItemGeneric
	{
		
		private EBoostableArea _area;
		private int _value;
		public ItemVitamin (ItemsVitaminsRow aVitaminRow)
		{
			_name = aVitaminRow._ItemName;
			_description = aVitaminRow._ItemDescription;
			_tintColour = new Color(aVitaminRow._SpriteTintR/255,aVitaminRow._SpriteTintG/255,aVitaminRow._SpriteTintB/255,aVitaminRow._SpriteTintA/255);
			_spritePrefab = aVitaminRow._Sprite;
			_itemType = EItemType.Vitamin;
			_softCost = aVitaminRow._SoftCurrency;
			this._hardCost = aVitaminRow._HardCurrency;
			this._id = aVitaminRow._ID;
			/*
			BoostAccuracy,BoostAgility,BoostRangeAtck,BoostRangeDef,BoostMeleeAtck,BoostMeleeDef,BoostSpeed,BoostAll,BoostXP
			*/
			switch(aVitaminRow._BoostArea) {
				case("BoostAccuracy"):_area = EBoostableArea.BoostAccuracy;break;
				case("BoostAgility"):_area = EBoostableArea.BoostAgility;break;
				case("BoostRangeAtck"):_area = EBoostableArea.BoostRangeAtck;break;
				case("BoostRangeDef"):_area = EBoostableArea.BoostRangeDef;break;
				case("BoostMeleeAtck"):_area = EBoostableArea.BoostMeleeAtck;break;
				case("BoostMeleeDef"):_area = EBoostableArea.BoostMeleeDef;break;
				case("BoostSpeed"):_area = EBoostableArea.BoostSpeed;break;
				case("BoostAll"):_area = EBoostableArea.BoostAll;break;
				case("BoostLevel"):_area = EBoostableArea.BoostXP;break;
			}
			
			_value = aVitaminRow._BoostValue;
			
		}
		public int boostValue {
			get {
				return _value; 
			}
		}
		public EBoostableArea boostArea {
			get {
				return _area;
			}
		}
		
	}
}

