// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Items
{
	public interface ITMItem
	{
		string Name();
		string Description();
		EItemType Type();
		Texture texture();
		int HardCost();
		int SoftCost();
		int ID();
		
	}
}

