// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Items
{
	public interface ITMItemLibrary
	{
		string Name();
		BetterList<ITMItem> allItems();
		BetterList<ITMItem> nonPremiumItems();
		BetterList<ITMItem> paidItems();
		ITMItem randomItem();
		void addItemsTo(BetterList<ITMItem> aItems);
		ITMItem itemByID(int aID);
	}
}
