// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Google2u;
using UnityEngine;


namespace Items
{
	public class PlayerBoostItem : ItemGeneric
	{
		public float itemStrength;
		public EPlayerBoostType boostType;
		public int time;
		public PlayerBoostItem (ItemsPlayerBoostsRow aRow)
		{
			this._name = aRow._itemname;
			this._description = aRow._itemdescription;
			this._hardCost = (int) aRow._hardcurrency;
			this._softCost = (int) aRow._softcurrency;
			this._spritePrefab = aRow._sprite;
			this._id = (int) aRow._id;
			
			this.itemStrength = (float) aRow._strength;
			switch(aRow._type) {
				case("BoostXP"):boostType = EPlayerBoostType.XPBoost;break;
				case("Repel"):boostType = EPlayerBoostType.Repel;break;
			}
			time = aRow._seconds;
			_itemType = EItemType.PlayerBoost;
			this._tintColour = new Color((float) aRow._spritetintr/255f,(float) aRow._spritetintg/255f,(float) aRow._spritetintb/255f,(float) aRow._spritetinta/255f);
		}
		
	}
}

