// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace ManageMonster
{
	public class ManageMonsterStats : MonoBehaviour
	{
		public UILabel hp;
		public UILabel meleeAtck;
		public UILabel meleeDef;
		public UILabel rangeAtck;
		public UILabel rangeDef;
		public UILabel speed;
		public UILabel agility;
		public UILabel support;
		
		public UILabel monsterDescription;
		public UILabel primaryElement;
		public UILabel secondaryElement;
		public UILabel evolvesAt;
		
		public ManageMonsterStats ()
		{
		}
		public void initMonster(MonsterDataMain aMonster) {
			hp.text = aMonster.MaxHP.ToString();
			meleeAtck.text = aMonster.meleeAttack.ToString();
			meleeDef.text = aMonster.meleeDefense.ToString();
			rangeAtck.text = aMonster.rangeAttack.ToString();
			rangeDef.text = aMonster.rangeDefense.ToString();
			speed.text = aMonster.speed.ToString();
			agility.text = aMonster.agility.ToString();
	//		support.text = aMonster.support.ToString();
			if(monsterDescription!=null)
				monsterDescription.text = aMonster.monsterBreedRef.description; else {
					Debug.LogWarning("Monster Description in ManageMonsterStats Was Null");
				}
			primaryElement.text = aMonster.monsterBreedRef.PrimaryElement.Name;
			if(aMonster.monsterBreedRef.SecondaryElement!=null) {
				this.secondaryElement.text = aMonster.monsterBreedRef.SecondaryElement.Name;
			} else {
				this.secondaryElement.text = "NONE";
			}
			if(aMonster.monsterBreedRef.evolvesTo!=null&&aMonster.monsterBreedRef.evolvesTo.Name!="No Creature") {
				this.evolvesAt.text = "LVL "+aMonster.monsterBreedRef.evolvesAt;
			} else {
				this.evolvesAt.text = "N/A";
			}
		}
		void Update() {
		}
		void Start() {
		}
	}
}

