// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace ManageMonster
{
	public class ManageMonsterPassiveEffect : MonoBehaviour
	{
		public UILabel effectName;
		public UILabel effectDescription;
		
		public ManageMonsterPassiveEffect ()
		{
		}
		
		public void initMonster(MonsterDataMain aMonster) {
			effectName.text = aMonster.passiveEffect.name;
			effectDescription.text = aMonster.passiveEffect.description;
		}
		
	}
}

