// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace ManageMonster
{
	public class ManageMonsterBase : MonoBehaviour
	{	
		private ManageMonsterLeftSide _leftSide;
		public MonsterDataMain monster;
		public ManageMonsterBase ()
		{
		}
		public ManageMonsterLeftSide leftSide {
			get {
				if(_leftSide==null) {
					_leftSide = this.GetComponent<ManageMonsterLeftSide>();
				}
				return _leftSide;
			}
		}
		public void initMonster(MonsterDataMain aMonster) {
			ManageMonsterLeftSide leftSide = this.GetComponent<ManageMonsterLeftSide>();
			if(leftSide) {
				leftSide.initMonster(aMonster);
			}
			monster = aMonster;
			
			GameObject bg = BattleBGLibrary.getBGForMonsterType(aMonster.elementType);
		}
	}
}

