// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
[Flags]
public enum EBoostableArea
{
	BoostAccuracy = 1,
	BoostAgility = 2,
	BoostRangeAtck = 4,
	BoostRangeDef = 8,
	BoostMeleeAtck = 16,
	BoostMeleeDef = 32,
	BoostSpeed = 64,
	BoostAll = BoostAccuracy|BoostAgility|BoostRangeDef|BoostMeleeAtck|BoostMeleeDef|BoostSpeed,
	BoostXP = 128,
	
	
}

