// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
[Flags]
public enum EItemUsageType
{
	UseFailed = 1,
	Consumed = 2,
	Equipped = 4,
	CouldUse = 8,
}

