// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
[Flags]
public enum EMoveTreeUnlockFailureReason
{
	Success = 0x00,
	LevelFailure = 0x01,
	PreceedingMoveFailure = 0x02,
	EvolutionFailure = 0x04,
	FullyUnlockedFailure = 0x08,
}


