// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
[Flags]
	public enum EStatusEffects
	{
		None = 0,
		Paralyze = 1,
		Sleep = 2,
		Poison = 4,
		Freeze = 8,
		Flinch = 16,
		Confusion = 32,
		Burn = 64,

	}

