// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
[Flags]
public enum EWhenToApply
{
		BattleStart = 1,
		WhenMyHPLowerThan = 2,
		WhenMyHPHigherThan = 4,
		WhenHitByMoveType = 8,
		WhenAttackingWithMoveType = 16,
		WhenStatusEffectsSuffered = 32,
		WhenOpponentHasStatusEffect = 64,
		WhenDefendentIsType = 128,
		WhenAttackerIsType = 256,
		WhenAlliesAreType = 512,
		WhenHit = 1024,
		AtEndOfMoveQueue = 2048,
//		WhenUsingMoveOfType = 4096,
		WhenTheirHPLowerThan = 8192,
		WhenTheirHPHigherThan = 16384,
		WhenHitByRangeType = 32768,
		WhenHitByMoveTypeAtEndOfMoveQueue = 32768*2,
		WhenOneOpponentisType = 32768*4,
		WhenOneOpponentisSameAsEffectOwner = 32768*8,
}
