// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Battles;
using Google2u;
using System.Collections.Generic;
using UnityEngine;
using PixelCrushers.DialogueSystem;
using PixelCrushers.DialogueSystem.ChatMapper;


public class NPCBattlesLibrary
{
		public NPCBattlesLibrary ()
		{
		
		}
		public static void initNPCBattleVariables(DialogueDatabase aDatabase) {
		
		//	v.fields.Add(new Field(all[i]._BATTLENAME,"0",FieldType.Number));
		
			DialogueManager.PreloadMasterDatabase();
			List<NPCBattlesRow> all = NPCBattles.Instance.Rows;
		
			for(int i = 0;i<all.Count;i++) {
				string varName = DialogueLua.GetVariable(all[i]._BattleName).AsString;
				if(varName.Length==0||varName=="nil") {
						DialogueLua.SetVariable(all[i]._BattleName,500);
					} else {
					}
			}
		} 
		public static BetterList<NPCBattleMonstersRow> getMonstersForBattle(string aBattleName) {
			BetterList<NPCBattleMonstersRow> r = new BetterList<NPCBattleMonstersRow>();
			List<NPCBattleMonstersRow> l = NPCBattleMonsters.Instance.Rows;
			for(int i = 0;i<l.Count&&r.size<3;i++) {
				if(l[i]._BattleName==aBattleName) {
					r.Add(l[i]);
				}
			}
			if(r.size==0) {
				Debug.LogError("Battle: "+aBattleName+" Had no monsters!");
			}
			return r;
		}
		public static BattleInit getNPCBattleData(string aBattleName) {
			List<NPCBattlesRow> all = NPCBattles.Instance.Rows;
			for(int i = 0;i<all.Count;i++) {
				if(all[i]._BattleName==aBattleName) {
					 
					return new BattleInit(all[i],getMonstersForBattle(aBattleName));
				}
			}
			return null;
		}
		
}

