// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;


namespace Battles
{
	public class BattleMonsterWithAnimations : BattleMonsterBase
	{
		private RuntimeAnimatorController _animC;
		private bool _proceedEvolution;
		private int _xpToAdd;
		private GameObject _targetOptionEffect;
		private GameObject _targetOptionOrb;
		public bool completedEvolving = false;
		public BattleMonsterWithAnimations ()
		{
		}
		public void Awake() {
			_anim = this.GetComponent("Animator") as Animator;
			_animC = _anim.runtimeAnimatorController;
			_anim.speed = UnityEngine.Random.Range(0.95f,1.05f);
		}
		
		public void ChangeLayerTo(string aNewLayer) {
			this.gameObject.layer = 15;
			foreach (Transform child in transform) {
				ChangeLayerTo (child,aNewLayer);
			}
		}
		public void ChangeLayerTo(Transform aChild,string aNewLayer) {
			aChild.gameObject.layer = 15;
			foreach (Transform child in aChild.transform) {
				ChangeLayerTo (child,aNewLayer);
			}
		}
		protected GameObject getEffect(string aEffect) {
			if(this==null) {
				return null;
			}
			if(Resources.Load("Battles/StatusEffects/"+aEffect)==null) {
				Debug.Log(aEffect+" could not load particle effect");
				return null;
			}
			
			if(this.gameObject!=null) {
				
				GameObject prefab = UnityEngine.Object.Instantiate(Resources.Load("Battles/StatusEffects/"+aEffect)) as GameObject;
				prefab.transform.parent = this.gameObject.transform;
				putParticlesInfront(prefab);
				return prefab;
			} else {
				return null;
			}
		}
		
		public static void putParticlesInfront(GameObject aObject) {

				aObject.GetComponent<ParticleSystem>().GetComponent<Renderer>().sortingLayerName = "ParticleLayer";
				ParticleSystem[] children = aObject.GetComponentsInChildren<ParticleSystem>();
				for(int j = 0;j<children.Length;j++) {
					children[j].GetComponent<Renderer>().sortingLayerName = "ParticleLayer";
				}
			
		}
		
		private GameObject getEvolutionEffect(string aEffect) {
			if(Resources.Load("Battles/Evolution/"+aEffect)==null) {
				Debug.Log("Evolution could not load particle effect");
				return null;
			}
			GameObject prefab = UnityEngine.Object.Instantiate(Resources.Load("Battles/Evolution/"+aEffect)) as GameObject;
			return prefab;
		}
		public void showEvolveAnim() {
			
			GameObject evolve = getEvolutionEffect("CFXM2_PowerAura");
			evolve.transform.parent = this.transform.parent;
			evolve.transform.localScale = this.transform.localScale;
			evolve.layer = 14;
			evolve.transform.localPosition = this.transform.localPosition;
			ParticleSystem[] childr = evolve.GetComponentsInChildren<ParticleSystem>();
			for(int i = 0;i<childr.Length;i++) {
				childr[i].gameObject.layer = 14;
			}
			StartCoroutine(evolveProcedure());
			BattleControllerWithParticleEngines.putParticlesInfront();
		}
		private IEnumerator evolveProcedure() {
			yield return new WaitForSeconds(1.25f);
			iTween.FadeTo(this.gameObject,0f,2f);
			yield return new WaitForSeconds(2f);
			completedEvolving = true;
			this.monster.evolve();
			_proceedEvolution = true;
			
			GameObject burst = getEvolutionEffect("CFXM3_Hit_Light_B_Air");
			burst.transform.parent = this.transform.parent;
			burst.transform.localScale = this.transform.localScale;
			burst.layer = 14;
			burst.transform.localPosition = this.transform.localPosition;
			BattleControllerWithParticleEngines.putParticlesInfront();
			
		}
		 
		public void pauseEvolution() {
			
			iTween.FadeTo(this.gameObject,1f,0.01f);
			this.StopAllCoroutines ();
		}
		public GameObject createCaughtAnimEffect(int aStage) {
			if(Resources.Load("Battles/CaughtAnims/Stage"+aStage+"Anim")==null) {
				Debug.Log("CaughtEffect could not load particle effect");
				return null;
			}
			GameObject prefab = UnityEngine.Object.Instantiate(Resources.Load("Battles/CaughtAnims/Stage"+aStage+"Anim")) as GameObject;
			
			if(aStage==2) {
				prefab.transform.position = this.transform.localPosition;
			} else
			prefab.transform.position = this.SpawnPosition;
			BattleControllerWithParticleEngines.putParticlesInfront();
			return prefab;
		}
		
		public void doStatLoweringAnim() {
			GameObject g = getEffect("StatLowering");
			g.transform.position = this.SpawnPosition;
		}
		public void doStatRaisingAnim() {
			GameObject g = getEffect("StatRaising");
			g.transform.position = this.SpawnPosition;
		}
		
		public void showStatusEffect(EStatusEffects aEffect) {
			switch(aEffect) {
				case(EStatusEffects.Flinch):
					GameObject flinch = getEffect("FlinchEffect");
					if(flinch!=null)
					flinch.transform.position = this.SpawnPosition;
				break;
			case(EStatusEffects.Confusion):
					GameObject confusion = getEffect("ConfuseEffect");
					if(confusion!=null)
						confusion.transform.position = this.ConfuseSpawnPosition;
				break;
			case(EStatusEffects.Poison):
					GameObject poisoned = getEffect("PoisonedEffect");
					if(poisoned!=null) 
					poisoned.transform.position = this.ConfuseSpawnPosition;
					break;
				
			case(EStatusEffects.Freeze):
				GameObject frozen = getEffect("FrozenEffect");
				if(frozen!=null) 
					frozen.transform.position = this.ConfuseSpawnPosition;
				break;
			case(EStatusEffects.Paralyze):
				GameObject paralyze = getEffect("ParalyzeEffect");
				if(paralyze!=null) 
					paralyze.transform.position = this.ConfuseSpawnPosition;
				break;
			case(EStatusEffects.Burn):
				GameObject burn = getEffect("BurnEffect");
				if(burn!=null) 
					burn.transform.position = this.ConfuseSpawnPosition;
				break;
			case(EStatusEffects.Sleep):
				GameObject sleep = getEffect("SleepEffect");
				if(sleep!=null) {
					sleep.transform.position = this.ConfuseSpawnPosition;
				}
				break;
			}
			BattleControllerWithParticleEngines.putParticlesInfront();
		}
		IEnumerator returnToIdleAnim(){   
			
			yield return new WaitForSeconds(0.5f); 
			_anim.SetInteger("AnimState",(int) EMonsterAnimations.Idle);
		}
		public void fadeInMakeup() {
			if(this._monsterRef.restingStatus==ERestingStatus.Awake&&_makeupFaded) {
				iTween.FadeTo(this._monsterMakeup.gameObject,1f,1f);
				_makeupFaded = false;
			}
		}
		protected Animator myAnimator {
		
			get {
				if(_anim==null)
					_anim = this.GetComponent("Animator") as Animator;
				return _anim;
			}
		}
		public void doIdleAnimation() {
			if(this._monsterRef.restingStatus==ERestingStatus.Awake&&!this._monsterRef.lingeringEffects.hasEffect(EStatusEffects.Sleep)) {
				myAnimator.SetInteger("AnimState",(int) EMonsterAnimations.Idle);
				fadeInMakeup();
			}
			
		}
		
		public void doAttackAnimation() {
			if(this._monsterRef.restingStatus==ERestingStatus.Awake&&!this._monsterRef.lingeringEffects.hasEffect(EStatusEffects.Sleep)) {
				myAnimator.SetInteger("AnimState",(int) EMonsterAnimations.Idle);
				_anim.SetTrigger("ScratchAttack");
				fadeInMakeup(); 
			}
		}
		
		public void doDefenseAnimation() {
			if(this._monsterRef.restingStatus==ERestingStatus.Awake&&!this._monsterRef.lingeringEffects.hasEffect(EStatusEffects.Sleep)) {
				_anim.SetTrigger("HitAnim");
				fadeInMakeup();
			}
		}  
		public void addXP(int aXPToAdd) {
			_xpToAdd = aXPToAdd;
		}  
		public void showTargetOption() {
			removeTargetOption();
			if(Resources.Load("Battles/TargetMonsterLight")==null) {
				Debug.Log("Could not load target effect");
				return;
			}
			if(this.monster.restingStatus==ERestingStatus.Awake) {
				GameObject prefab = UnityEngine.Object.Instantiate(Resources.Load("Battles/TargetMonsterLight")) as GameObject;
				prefab.transform.localScale = new Vector3(1f,1f,1f);
				prefab.transform.SetParent(this.transform.parent);
				prefab.transform.localPosition = this.transform.localPosition;
				prefab.tag = "ParticleSystems";
				
				_targetOptionEffect = prefab;
			/*	
				prefab = UnityEngine.Object.Instantiate(Resources.Load ("Battles/MoveEffects/SelectThisMonster")) as GameObject;
				prefab.transform.localScale = new Vector3(1f,1f,1f);
			//	Vector3 pos = prefab.transform.localPosition;
			//	pos.y += 3;
				prefab.transform.parent = this.transform;
				prefab.tag = "ParticleSystems";
				prefab.transform.localPosition = new Vector3(0f,3f,0f);
				this._targetOptionOrb = prefab;*/
				putParticlesInfront(); 
			}
		}
		public void removeTargetOption() {
			if(_targetOptionEffect!=null) {
				Destroy(_targetOptionEffect.gameObject);
				_targetOptionEffect = null;
			}
			if(_targetOptionOrb!=null) {
				Destroy (_targetOptionOrb.gameObject);
				_targetOptionOrb = null;
			}
		}
		
		public static void putParticlesInfront() {
			GameObject[] allParticles = GameObject.FindGameObjectsWithTag("ParticleSystems");
			for(int i = 0;i<allParticles.Length;i++) {
				
				allParticles[i].GetComponent<ParticleSystem>().GetComponent<Renderer>().sortingLayerName = "MiddleLayer";
				ParticleSystem[] children = allParticles[i].GetComponentsInChildren<ParticleSystem>();
				for(int j = 0;j<children.Length;j++) {
					children[j].GetComponent<Renderer>().sortingLayerName = "MiddleLayer";
				}
			}
		}
		
		public void Update() {
			if(_proceedEvolution) {
				_proceedEvolution = false;
				GameObject g = UnityEngine.Object.Instantiate(this._monsterRef.prefab) as GameObject;
				g.name = "Evolved State";
				g.transform.parent = this.gameObject.transform.parent;
				g.transform.position = this.gameObject.transform.position;
				g.transform.localPosition = this.gameObject.transform.localPosition;
				g.transform.localScale = this.gameObject.transform.localScale;
				g.layer = this.gameObject.layer;
				ChangeLayerTo(g.transform,"UI");
				SpriteRenderer[] rend = this.gameObject.GetComponentsInChildren<SpriteRenderer>();
				for(int i = 0;i<rend.Length;i++) {
					Destroy (rend[i].gameObject);
				}
				
				iTween.ScaleFrom(g,new Vector3(0f,0f,0f),0.5f);
				Renderer[] allRenderers = g.GetComponentsInChildren<Renderer>();
				for(int i = 0;i<allRenderers.Length;i++) {
					allRenderers[i].sortingLayerName = "MonsterLayer3";
					
				}
					
			}
			
			if(_xpToAdd>200.0f) {
				_xpToAdd-=50;
				this.monster.addXP(50.0f);
			} else if(_xpToAdd>100.0f) {
				_xpToAdd-=10;
				this.monster.addXP(10.0f);
			} else if(_xpToAdd>1.0f) {
				
				_xpToAdd-=1;
				PlayerMain.REF.allowMonsterSave = false;
				this.monster.addXP(1.0f);
			}
		}
	}
}

