// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UMA;


namespace UMA
{
	public class MyRaceDNAConverterBehaviour : DnaConverterBehaviour
	{
		
		static bool builtHashes = false;

		
		static protected int neckAdjustHash;
		static protected int spineAdjustHash;

		public override void Prepare()
		{
			if (builtHashes)
				return;
			
			neckAdjustHash = UMAUtils.StringToHash("NeckAdjust"); 
			spineAdjustHash = UMAUtils.StringToHash("SpineAdjust");

			builtHashes = true;
		}
	}
}

