// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public class AdditionalWeaknesses
{
	private ElementalType _weakness;
	private byte _turns;
	public AdditionalWeaknesses (ElementalType aElement,byte aTurns)
	{
		_weakness = aElement;
		_turns = aTurns;
	}
	
	public ElementalType type {
		get {
			return _weakness;
		}
	}
	public byte turnsRemaining {
		get {
			return _turns;
		}
		set {
			_turns = value;
		}
	}
}

