// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using Items;


namespace worldstore
{
	public class StoreSingleItem : MonoBehaviour
	{
		public UILabel itemTitle;
		public UILabel itemCost;
		public UISprite itemBagLabel;
		
		public UITexture itemSprite;
		public UILabel amountOwned;
		public delegate void OnItemSelected(ITMItem aItem);
		public event OnItemSelected itemSelected; 
		private ITMItem _item;
		
		private bool _active = false;
		public StoreSingleItem ()
		{
		}
		public void initButton(ITMItem aItem) {
			itemTitle.text = aItem.Name();

			_item = aItem;
			active = true;
			if(itemBagLabel==null) {
				itemBagLabel = this.transform.FindChild("Price Container").FindChild("TerraCoinImg").gameObject.GetComponent<UISprite>();
			}
			if(itemCost==null) {
				itemCost = this.transform.FindChild("Price Container").FindChild("TerraCoinValue").gameObject.GetComponent<UILabel>();
			}
			itemSprite = this.GetComponentInChildren<UITexture>();
			itemSprite.mainTexture = aItem.texture();
			
			if(aItem.SoftCost()>0) {
				itemCost.text = aItem.SoftCost().ToString();
				itemBagLabel.spriteName = "terracoins";
			} else {
				itemCost.text = aItem.HardCost().ToString();
				itemBagLabel.spriteName = "terradollars";
			}
		}
		public bool active {
			get {
				return _active;
			}
			set {
				_active = value;
				this.gameObject.SetActive(_active);
			}
		}
		public void onButtonClicked() {
			if(itemSelected!=null) {
				itemSelected(this._item);
			}
		}
		
	}
}

