// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using Items;
using Utils;

public class WorldStoreItemFull : MonoBehaviour
{
	public UILabel itemTitle;
	public UILabel itemCost;
	public UISprite bagIcon;
	public UILabel itemDescription;
	public UITexture itemTexture;
	public UILabel amountOwned;
	private ITMItem _itemRef;
	private AlertQuestionWindow _questionWindow;
	public WorldStoreItemFull ()
	{
	}
	public void init(ITMItem aItem) {
		_itemRef = aItem;
		itemTitle.text = aItem.Name();
		itemDescription.text = aItem.Description();
		if(aItem.SoftCost()>0) {
			itemCost.text = aItem.SoftCost().ToString();
			bagIcon.spriteName = "terracoins";
		} else {
			itemCost.text = aItem.HardCost().ToString();
			bagIcon.spriteName = "terradollars";
		}
		
		
		/*
		UISprite newSprite = aItem.Sprite();
		if(newSprite!=null) {
			
			Destroy (itemSprite);
			itemSprite = newSprite;
			newSprite.transform.parent = currentParent;
			newSprite.transform.localScale = currentScale;
			newSprite.transform.position = new Vector3(0f,0f,0f);
			newSprite.transform.localPosition = new Vector3(0f,0f,0f);
			newSprite.depth = currentSpriteOrder;
		}*/
		itemTexture.mainTexture = aItem.texture();
		amountOwned.text = PlayerMain.REF.amountOwned(aItem).ToString();
	}
	public void onGoBack() {
	
	}
	private void onLeftAnswer() {
		removeWindowReferences();
	}
	private void onBuyMoreTerraDollars() {
		removeWindowReferences();
		AlertGUI.REF.BuyMoreTerraDollars("","");
	}
	private void removeWindowReferences() {
		
		_questionWindow.onLeftAnswer -= onLeftAnswer;
		_questionWindow.onAnswered -= onBuyMoreTerraDollars;
		_questionWindow.onAnswered -= onBuyMoreTerraCoins;
		_questionWindow = null;
	}
	private void onBuyMoreTerraCoins() {
		removeWindowReferences();
		AlertGUI.REF.BuyMoreTerraCoins();
	}
	public void onBuyItem() {
		if(PlayerMain.REF.canBuyItem(_itemRef)) {
			PlayerMain.REF.changeHardCurrency(_itemRef.HardCost()*-1);
			PlayerMain.REF.changeSoftCurrency(_itemRef.SoftCost()*-1);
			PlayerMain.REF.addToInventory(_itemRef);
			init (_itemRef);
		} else {
			if(_itemRef.HardCost()>PlayerMain.REF.hardCurrency) {
				AlertQuestionWindow window = AlertGUI.REF.DoQuestionAlert("Not Enough Terra Dollars","You cannot currently afford "+_itemRef.Name()+". Buy more Terra Dollars?","Yes","No");
				window.onLeftAnswer += onLeftAnswer;
				window.onAnswered += onBuyMoreTerraDollars;
				_questionWindow = window;
			} else {
				AlertQuestionWindow window = AlertGUI.REF.DoQuestionAlert("Not Enough Terra Dollars","You cannot currently afford "+_itemRef.Name()+". Buy more Terra Coins?","Yes","No");
				window.onLeftAnswer += onLeftAnswer;
				window.onAnswered += onBuyMoreTerraCoins;
				_questionWindow = window;
			}
		}
	}
}

