// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public enum ERareity
{
	VeryCommon = 0,
	Common = 1,
	QuiteCommon = 2,
	Rare = 3,
	VeryRare = 4,
	SuperRare = 5

}


