// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


[System.Serializable]
public class SpawnPointOptions
{
	public GameObject monsterToSpawn;
	public int levelLow;
	public int levelHigh;
	public int hourToStart;
	public int hourToFinish;

	public ERareity rareness;

	public SpawnPointOptions ()
	{
	}
}


