// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using GoogleFu;
using UnityEngine;
public class SpawnArea
{
	private byte _trigger;
	private BetterList<SpawnAreaMonster> _monsters = new BetterList<SpawnAreaMonster>();
	private string _battleBG;
	public static float SPAWN_MULTIPLIER = 0.2f;
	public SpawnArea (MapSpawnsRow aInitData)
	{
		_trigger = (byte) aInitData._trigger;
		_battleBG = aInitData._spawnmapbg;
		if(aInitData._monstera!="") {
			_monsters.Add (new SpawnAreaMonster(aInitData._monstera,(byte) aInitData._monsterlevela,aInitData._monsterafrequency,aInitData._spawnmusic));
		}
		
		if(aInitData._monsterb!="") {
			_monsters.Add (new SpawnAreaMonster(aInitData._monsterb,(byte) aInitData._monsterlevelb,aInitData._monsterbfrequency,aInitData._spawnmusic));
		}
		
		if(aInitData._monsterc!="") {
			_monsters.Add (new SpawnAreaMonster(aInitData._monsterc,(byte) aInitData._monsterlevelc,aInitData._monstercfrequency,aInitData._spawnmusic));
		}
		
		if(aInitData._monsterd!="") {
			_monsters.Add (new SpawnAreaMonster(aInitData._monsterd,(byte) aInitData._monsterleveld,aInitData._monsterdfrequency,aInitData._spawnmusic));
		}
		
	}
	
	public string battleBG {
		get {
			return _battleBG;
		}
	}
	
	public SpawnAreaMonster canProvideBattle() {
		
		for(byte c = 0; c < _monsters.size ; c++) {
			
			float r = UnityEngine.Random.Range(0.0f,1.0f);
			if(r<_monsters[c].percentChance*0.05*SpawnArea.SPAWN_MULTIPLIER) {
				if(_monsters[c].monster!=null)
					return _monsters[c];
			}
		}
		return null;
	}
	public byte trigger {
		get {
			return _trigger;
		}
	}
}

