// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


public class SpawnAreaMonster
{
	private MonsterLibraryRecord _monster;
	private byte _level;
	private float _percentChance;
	public string battleTrack;

	public SpawnAreaMonster (string aMonsterName,byte aLevel,float aChance,string aBattleTrack) 
	{
		battleTrack = aBattleTrack;
		_percentChance = aChance;
		_level = aLevel;
		_monster = MonsterLibrary.REF.getMonster(aMonsterName);
		if(_monster==null) {
			Debug.LogWarning("No monster by name of: "+aMonsterName);
		}
	}
	public MonsterLibraryRecord monster {
		get {
			return _monster;
		}
		
	}
	
	public byte level {
		get {
			return _level;
		}
	}
	public float percentChance {
		get {
			return _percentChance;
		}
	}
}

