// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Battles
{
	public class MoveButtonScript : MonoBehaviour
	{
		public GameObject[] activeStars;
		public GameObject[] inactiveStars;
		public UILabel title;
		public UIProgressBar progressBar;
		public GameObject moveType;
		public bool isLit = false;
		public MoveButtonScript ()
		{
		}
		public void handleAutoSelect(bool aIsLit) {
			isLit = aIsLit;
			this.GetComponent<BoxCollider2D>().enabled = aIsLit;
		}
		public void OnDisable() {
		}
		public void initFromMove(SelectedMoveData aMoveData,MonsterDataMain aMonster) {
			if(!aMoveData.validMove) {
				this.gameObject.SetActive(false);
				isLit = false;
				return;
			} else {
				float energy = (float) aMoveData.moveData.energy;
				float maxEnergy = (float) MovesLib.REF.maxMoveEnergy;
				gameObject.SetActive(true);
				
				this.progressBar.value = energy / maxEnergy;;
				if(aMoveData.moveData.energy<=aMonster.energy) {
					
					title.text = aMoveData.moveData.Name.ToUpper();
					isLit = true;
				} else {
			//		title.text = "Not Enough Energy!".ToUpper();
					title.text = MovesLib.REF.struggleMove.Name;
					isLit = true;
				
				}
			}
		
			for(int i = 0;i<inactiveStars.Length;i++) {
				if(aMoveData.move.currentUnlockLevel>i) {
					activeStars[i].gameObject.SetActive(true);
					inactiveStars[i].gameObject.SetActive(false);
				} else {
					activeStars[i].gameObject.SetActive(false);
					inactiveStars[i].gameObject.SetActive(true);
				}
			}
			
		}
	}
}

