// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using PixelCrushers.DialogueSystem;


public class PlayerMain : PlayerWithMultiplayer
{
	public static PlayerMain REF;
		public PlayerMain ()
		{
			REF = this;
			base.PlayerDataWithMonsters();
		}

		///Initialises Player Data with some debug data, 3 monsters and a basic inventory
		public virtual void initForDebug() {
			base.initForDebug();
		}
		
		public string name {
			get {
				Lua.Result r = DialogueLua.GetActorField("Player","Name");
				if(r.AsString.Length==0) {
					return "Demo";
				}


				return r.AsString;
			}
		}

		public virtual void saveAll() {
			
		}


}

