// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using utils;


public class PlayerBase
{
	private Doorway _futureDoorway;
	private int _hardCurrency;
	private int _softCurrency;
	
	
	public delegate void OnCurrencyChanged(int aOldValue);
	public event OnCurrencyChanged onSoftCurrencyChanged; 
	public event OnCurrencyChanged onHardCurrencyChanged; 
	public PlayerBase ()
	{
		if(_futureDoorway==null) {
			_futureDoorway = MapLibrary.getInitDoorway();
		}
	}

	public int hardCurrency {
		get {
			return _hardCurrency;
		}
		set {
			_hardCurrency = value;
		}
	}
	public int softCurrency {
		get {
			return _softCurrency;
		}
		set {
			_softCurrency = value;
		}
	}
	
	public bool changeSoftCurrency(int aAmount) {
		if(_softCurrency+aAmount>=0) {
			_softCurrency += aAmount;
			if(onSoftCurrencyChanged!=null) {
				onSoftCurrencyChanged(_softCurrency-aAmount);
			}
			
			SaveGameUtils.REF.SavePlayerData();
			return true;
		}
		return false;
	}
	
	public bool changeHardCurrency(int aAmount) {
		if(_hardCurrency+aAmount>=0) {
			_hardCurrency += aAmount;
			if(onHardCurrencyChanged!=null) {
				onHardCurrencyChanged(_hardCurrency-aAmount);
			}
			SaveGameUtils.REF.SavePlayerData();
			return true;
		}
		return false;
	}
	public virtual void initForDebug() {

	}
	public virtual void saveAll()
	{

	}
	public Doorway futureDoorway {
		set {
			_futureDoorway = value;
		}
		get {
			return _futureDoorway;
		}
	}
}

