// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Items
{
	public class InventoryItemDisplay : MonoBehaviour
	{
		public UILabel itemTitle;
		public UILabel itemCount;
		public InventoryItem item;
		
		public UITexture texture;
		public delegate void OnItemClicked(InventoryItem aItem);
		public event OnItemClicked onClicked; 
		public bool listening = false;
		public InventoryItemDisplay ()
		{
		
		}
		
		public void initItem(InventoryItem aItem) {
			itemTitle.text = aItem.item.Name();
			texture = transform.FindChild("Texture").gameObject.GetComponent<UITexture>();
			texture.mainTexture = aItem.item.texture();
			itemCount.text = aItem.count.ToString();
			UIButton b = this.GetComponent<UIButton>();
			b.onClick.Add(new EventDelegate(this,"onItemClicked"));
			item = aItem;
			if(!listening) {
				listening = true;
				PlayerMain.REF.onInventoryChanged += onInventoryChanged;
			}
			
		}
		
		public void OnDisable() {
			listening = false;
			PlayerMain.REF.onInventoryChanged -= onInventoryChanged;
		}
		private void onInventoryChanged(InventoryItem aItem) {
			
			itemCount.text = item.count.ToString();
		}
		public void update(InventoryItem aItem) {
			itemCount.text = item.count.ToString();
			
		}
		public void onItemClicked() {
			if(onClicked!=null) {
				onClicked(item);
			}
		}
	}
}

