// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Google2u;
using UnityEngine;


public class ElementalType
{
	private int id = 0;
	private string name;
	private string description;
	private float strengthVsEarth;
	private float strengthVsWater;
	private float strengthVsIce;
	private float strengthVsAir;
	private float strengthVsFire;
	private float strengthVsArcane;
	private float strengthVsElectric;
	private int _binaryFlag = 0;
	private Color _color;
		public ElementalType (ElementTypesRow aRow)
		{
			id = aRow._ID; 
			name = aRow._ElementName;
			description = aRow._Description;
			strengthVsEarth = aRow._StrengthVsEarth;
			strengthVsWater = aRow._StrengthVsWater;
			strengthVsIce = aRow._StrengthVsIce;
			strengthVsAir = aRow._StrengthVsAir;
			strengthVsFire = aRow._StrengthVsFire;
			strengthVsArcane = aRow._StrengthVsArcane;
			strengthVsElectric = aRow._StrengthVsElectric;
			_binaryFlag = aRow._ElementFlag;
			_color = new Color(aRow._ElementalColorRed/255f,aRow._ElementalColorGreen/255f,aRow._ElementalColorBlue/255f,1.0f);
			//_color = new Color(aRow._ELEMENTALCOLORRED,aRow._ELEMENTALCOLORGREEN,aRow._ELEMENTALCOLORBLUE);
		}
		
		public int binaryFlag {
			get {
				return _binaryFlag;
			}
		}
		public Color color {
			get {
				return _color;
			}
		}
		public int ID {
			get {
				return id;		
			}
		}
	
	public float getWeaknessStrengthToElement(ElementalType aOther) {
		switch(aOther.Name) {
			case("Earth"):return strengthVsEarth;
			case("Water"):return strengthVsWater;
			case("Ice"):return strengthVsIce; 
			case("Air"):return strengthVsAir;
			case("Fire"):return strengthVsFire;
			case("Arcane"):return strengthVsArcane;
			case("Electric"):return strengthVsElectric;
		}
		return 1.0f;
	} 
	public string Name {
		get {
			return name;	
		}
	}
}

