// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using GoogleFu;
public class XPDevModelLib
{
	BetterList<XPDevModel> list = new BetterList<XPDevModel>();
	public static XPDevModelLib REF = new XPDevModelLib();
		public XPDevModelLib ()
		{
			List<XPDevelopmentModelsRow> rows = XPDevelopmentModels.Instance.Rows;
			for (int i = 0; i < rows.Count; i++) {
				XPDevModel devModel = new XPDevModel(rows[i]);
				list.Add(devModel);
			}
			
		}

		public XPDevModel getXPDevModel(string aName) {
			for (int i = 0; i < list.size; i++) {
				if(list[i].Name == aName) {
					return list[i];
				}
			}
			return null;
		}
}

