// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Google2u;
public class XPDevModel
{
	
	private int id;
	private string name;
	private string formula;
	private uint[] levels = new uint[101];
	public XPDevModel (XPDevelopmentModelsRow aInitData)
	{
		id = aInitData._ID;
		name = aInitData._Name;
		formula = aInitData._Formula;

		for (int i = 0; i < 101; i++) {
			uint v = 0;

			switch(formula) {
				case("4n^3/(5)"): v = (uint) (4*Math.Pow(i,3))/5;break;
				case("n^3"): v = (uint) Math.Pow(i,3);break;
				case("5n^3/(4)"): v = (uint) (5*Math.Pow(i,3))/4;break;
			}
			levels[i] = (uint) v;
		}
	}
	public uint[] Levels {
		get {
			return levels;	
		}
	}
	public string Name {
		get {
			return name;		
		}
	}
}

