// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Utils
{
	public class AlertWindowBuyFullRanchHeal : MonoBehaviour
	{
		public UILabel description;
		public const int RANCH_HEAL_COST = 10;
		public AlertWindowBuyFullRanchHeal ()
		{
		}
		public void init(string aMessage) {
			if(description!=null&&aMessage.Length>0) {
				description.text = aMessage;
			}
			Debug.Log ("init buy ranch heal");
		}
		public void onBuy() {
			if(!PlayerMain.REF.canUseRanchHeal()) {
				AlertGUI.REF.DoGeneralAlert("Full Health","All your Terra Monsters are already at full Health.");
				Destroy (this.gameObject);
				return;
			}
			if(PlayerMain.REF.hardCurrency<=RANCH_HEAL_COST) {
		//		AlertGUI.REF.BuyMoreTerraDollars("","");
				Destroy (this.gameObject);
			} else {
				PlayerMain.REF.changeHardCurrency(RANCH_HEAL_COST*-1);
				PlayerMain.REF.healAll();
				Destroy (this.gameObject);
			}
		}
		public void onCancel() {
			Destroy (this.gameObject);
		}
		
	}
}

