// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
public class AlertWindowMain : MonoBehaviour
{
	public UILabel title;
	public UILabel description;
	public AlertWindowMain ()
	{
	}
	public static void NewAlertWindow(string aTitle,string aDescription) {
		GameObject prefab = UnityEngine.Object.Instantiate(Resources.Load("Gui/PopupAlertWindow")) as GameObject;
		AlertWindowMain alert = prefab.GetComponent<AlertWindowMain>();
		alert.init(aTitle,aDescription);
		alert.transform.localScale = new Vector3(1.0f,1.0f,1.0f);
		GameObject g = GameObject.FindGameObjectWithTag("UIRoot");
		prefab.transform.parent = g.transform;
		alert.transform.localScale = new Vector3(1.0f,1.0f,1.0f);
	}
	
	public void onClose() {
		Destroy (this.gameObject);
	}
	public void init(string aTitle,string aDescription) {
		title.text = aTitle;
		description.text = aDescription;
	}
}

