// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class CurrencyWatcher : MonoBehaviour
{
	public UILabel currencyHolder;
	public bool isHardCurrency;
	private int _targetValue;
	private int _currentValue;
	public CurrencyWatcher ()
	{
	}
	
	void Start() {
		if(PlayerMain.REF!=null) {
			if(isHardCurrency) {
					PlayerMain.REF.onHardCurrencyChanged += onHardCurrencyChanged;
					_currentValue = PlayerMain.REF.hardCurrency;
				} else {
					PlayerMain.REF.onSoftCurrencyChanged += onSoftCurrencyChanged; 
					_currentValue = PlayerMain.REF.softCurrency;
				}
		}
		if(currencyHolder==null) {
			this.currencyHolder = this.GetComponentInChildren<UILabel>();
		}
		currencyHolder.text = Convert.ToString(_currentValue);
	}
	
	private void onHardCurrencyChanged(int aOldValue) {
		Debug.Log ("onHardCurrencyChanged: "+aOldValue+" / "+PlayerMain.REF.softCurrency);
		_targetValue = PlayerMain.REF.hardCurrency;
		_currentValue = aOldValue;
		currencyHolder.text = aOldValue.ToString();
	}
	private void onSoftCurrencyChanged(int aOldValue) {
		Debug.Log ("onSoftCurrencyChanged: "+aOldValue+" / "+PlayerMain.REF.softCurrency);
		_targetValue = PlayerMain.REF.softCurrency;
		_currentValue = aOldValue;
		currencyHolder.text = aOldValue.ToString();
	}
	void Update() {
		try {
		if(PlayerMain.REF!=null) {
			
			if(isHardCurrency)
				_targetValue = PlayerMain.REF.hardCurrency; else _targetValue = PlayerMain.REF.softCurrency;
			if(_targetValue!=_currentValue) {
				int incrementer = 0;
				if(_targetValue>_currentValue) {
					if(_targetValue>_currentValue+10) 
						incrementer = 10;
					incrementer = 1; 
				} else if(_targetValue<_currentValue) {
					if(_targetValue<_currentValue-10)
						incrementer = -10;
					incrementer = -1;
				}
				_currentValue += incrementer;
				currencyHolder.text = _currentValue.ToString();
			}
		}
		} catch(Exception e) {
			
		}
	}
}

