// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Utils
{
	public enum EGlobalSettings
	{
	 OfflineUnlocked = 0,
		
	Sounds = 1,
		Music = 2,
		PollBalances = 3,
		RateBox = 4,
	 MaxSize = 5,
	}
}

