// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace utils
{
	public enum EPlayerArray
	{
		Name =0,
		Gender = 1,
		SoftCurrency = 2,
		HardCurrency = 3,
		EMail = 4,
		Password = 5,
		LastUsedMap = 6,
		Quests = 7,
		Monsters = 8,
		MonsterCount = 9,
		Items = 10,
		RankingObjID = 11,
		XPBoostData = 12,
		RepelBoostData = 13,
		ArrayLength = 14,
	}
}

