// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;


namespace Maps
{
	public class LayerChangerScript : MonoBehaviour
	{
		private BoxCollider2D _collider;
		public string changeToThisLayer;
		public LayerChangerScript ()
		{
		
		}
		
		public void Awake() {
			_collider = this.GetComponent<BoxCollider2D>();
			StartCoroutine(SetCollidersAfter1Frame());
			
		}
		
		private IEnumerator SetCollidersAfter1Frame() {
			yield return null;
			
			GameObject player = GameObject.FindGameObjectWithTag("Player");
			//player.collider2D.
		
		}
		
		/// <summary>
		/// If we entered a trigger, check if it's a usable object. If so, update the selection
		/// and raise the SelectedUsableObject event.
		/// </summary>
		/// <param name='other'>
		/// The trigger collider.
		/// </param>
		
		/// <summary>
		/// If we entered a 2D trigger, check if it's a usable object. If so, update the selection
		/// and raise the SelectedUsableObject event.
		/// </summary>
		/// <param name='other'>
		/// The 2D trigger collider.
		/// </param>
		void OnTriggerEnter2D(Collider2D other) {
			if(other.gameObject.tag == "Player") {
				SpriteRenderer[] renderer = other.GetComponentsInChildren<SpriteRenderer>();
				for(int i = 0;i<renderer.Length;i++) {
					renderer[i].sortingLayerName = changeToThisLayer;
				}
				AvatarMover am = other.GetComponent<AvatarMover>();
				Debug.Log ("Changing Player to: "+changeToThisLayer);
				am.changeLayer(changeToThisLayer);
			}
		}
		
		
	}
}

