// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Battles
{
	public class CommentaryMessageSettings
	{
		public string message;
		public ECommentaryMessageType type;
		public ECommentaryMessagePosition position;
		
		public Vector3 screenPosition;
		
		public PassiveEffect passiveEffect;
		public BattleMonster monster;
		public CommentaryMessageSettings (string aMessage,ECommentaryMessageType aType,ECommentaryMessagePosition aMessagePosition,PassiveEffect aEffect,BattleMonster aMonster)
		{
			message = aMessage;
			type = aType;
			position = aMessagePosition;
			passiveEffect = aEffect;
			monster = aMonster;
			
		}
		
		public CommentaryMessageSettings (string aMessage,ECommentaryMessageType aType,Vector3 aScreenPosition)
		{
			message = aMessage;
			type = aType;
			screenPosition = aScreenPosition;
			
		}
		
	}
}

