// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
[Flags]
public enum EMoveBranch
{
	NoMove = 0,
	AttackingBranch1 = 1,
	AttackingBranch2 = 2,
	StatusEffectBranch = 4,
	SupportingBranch = 8,
}
