// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
[Flags]
public enum EPowerApplicationTypes
{
	Normal = 0x01,
	PowerIsHP = 0x02,
	PowerIsPercentOfHP = 0x04,
}

