// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

[Flags]
public enum ESplashRange
{
	Hit1Only = 1,
	SplashRange1 = 2,
	HitAll = 4,
	BoostMe = 8,
	Boost1AndMe = 16,
	Boost2 = 32,
	BoostAll = 64,
	BoostWholeField = 128,
	Boost1 = 256,
	RandomOpponent = 512,
	AllBoosts = Boost1|BoostWholeField|BoostAll|Boost2|Boost1AndMe|BoostMe,
	AllHits = HitAll|SplashRange1|Hit1Only|RandomOpponent,
}

